
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rifkyans
 */
public class fu extends javax.swing.JFrame {

    /**
     * Creates new form fu
     */
    public fu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelnama = new javax.swing.JLabel();
        btnklik = new javax.swing.JButton();
        labelnim = new javax.swing.JLabel();
        labelkelas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pemrograman Provis8");

        labelnama.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        labelnama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelnama.setText("Nama");

        btnklik.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnklik.setText("Klik I");
        btnklik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnklikMouseClicked(evt);
            }
        });

        labelnim.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        labelnim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelnim.setText("NIM");

        labelkelas.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        labelkelas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelkelas.setText("Kelas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelnama, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelkelas, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btnklik, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(162, 162, 162))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(labelnim, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(55, 55, 55)))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelnama)
                .addGap(18, 18, 18)
                .addComponent(labelnim)
                .addGap(18, 18, 18)
                .addComponent(labelkelas)
                .addGap(32, 32, 32)
                .addComponent(btnklik)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnklikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnklikMouseClicked
        // TODO add your handling code here:
        labelnama.setText("Nama: Rifky Arya Nur Salman");
        labelnim.setText("NIM : 10118347");
        labelkelas.setText("Kelas: IF - 8");
        JOptionPane.showMessageDialog(null, "Selamat Anda Berhasil Mengubah Label Nama, Nim, dan Kelas");
    }//GEN-LAST:event_btnklikMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnklik;
    private javax.swing.JLabel labelkelas;
    private javax.swing.JLabel labelnama;
    private javax.swing.JLabel labelnim;
    // End of variables declaration//GEN-END:variables
}
